version: "3.7"
services:

  backend:
    build: ./backend/
    ports:
      - "8000:8000"
    depends_on:
      - 'db'
    volumes:
      - ./config:/run/config
    secrets:
      - postgres_user
      - postgres_password
      - google_search_token

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - 'backend'
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/.next:/app/.next

  db:
    image: "postgres:15"
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - ./postgres/initialize.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./config:/run/config
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  google_search_token:
    file: ./secrets/google_search_token
  postgres_db:
    file: ./config/postgres_db
