version: "3.7"
services:

  backend:
    build: ./backend/
    depends_on:
      - 'db'
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - postgres_curios_schema
      - postgres_host
      - postgres_port
      - google_search_app
      - google_search_token

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - 'backend'
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/.next:/app/.next

  db:
    image: "postgres:15"
    container_name: "postgres"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - ./postgres/initialize.sql:/docker-entrypoint-initdb.d/create_tables.sql
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

secrets:
  postgres_user:
    file: ./secrets/postgres_user
  postgres_password:
    file: ./secrets/postgres_password
  postgres_db:
    file: ./secrets/postgres_db
  postgres_host:
    file: ./secrets/postgres_host
  postgres_port:
    file: ./secrets/postgres_port
  google_search_app:
    file: ./secrets/google_search_app
  google_search_token:
    file: ./secrets/google_search_token
  postgres_curios_schema:
    file: ./secrets/postgres_curios_schema

