version: "3.7"
services:

  backend:
    build: ./backend/
    depends_on:
      - 'postgres'
    volumes:
      - ./config/prod:/run/config
    secrets:
      - postgres_user
      - postgres_password
      - google_search_token

  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on:
      - 'backend'
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
      - ./frontend/.next:/app/.next

  postgres:
    image: "postgres:15"
    container_name: "postgres"
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    volumes:
      - ./postgres/initialize.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./config:/run/config
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

secrets:
  postgres_user:
    file: ./secrets/prod/postgres_user
  postgres_password:
    file: ./secrets/prod/postgres_password
  google_search_token:
    file: ./secrets/prod/google_search_token
  postgres_db:
    file: ./config/prod/postgres_db
